"""TrainingGroup — derive and run a group of related TrainConfigs.

A ``TrainingGroup`` takes one *base* :class:`TrainConfig` and a ``grid`` of
field overrides, and expands them into the cross-product of concrete
``TrainConfig`` variants. This is the entry point for parameter sweeps: vary a
few recipe fields, get one independent training run per combination.

Two design goals shape the API:

* ``get_train_configs()`` returns the derived ``TrainConfig`` list so you can
  inspect exactly what will run *before* launching anything.
* Invalid override paths (typos, fields that don't exist on the recipe/model/
  dataset, or values of the wrong type) raise immediately — at group
  construction and again in ``get_train_configs()`` — so a sweep never starts
  training only to die on the third variant an hour in.

Example::

    group = TrainingGroup(
        base=TrainConfig(
            model=Qwen3_6_35B(),
            dataset=ds,
            recipe=Qwen3_6_35b_Recipe(num_rollout=10),
        ),
        grid={
            "recipe.lr": [1e-6, 5e-6, 1e-5],
            "recipe.rollout_temperature": [0.8, 1.0],
        },
        name="lr-temp-sweep",   # optional; becomes the group_id (autogenerated if omitted)
    )

    for cfg in group.get_train_configs():   # 3 x 2 = 6 variants, validated
        print(cfg.training_run_id)

    results = group.train(max_parallel=3)   # list[TrainResult]

The ``name`` is the group's id: every run in the sweep is tagged with it so the
dashboard can group and filter them together. Pass one to get a stable,
human-readable id (it's slugified); omit it for an autogenerated ``group-<hex>``.
"""

from __future__ import annotations

import copy
import dataclasses as _dc
import difflib
import re
import secrets
from typing import Any

from modal_training_gym.common.train import TrainConfig, TrainLaunch
from modal_training_gym.common.train_result import TrainResult


class TrainingGroupError(ValueError):
    """Raised when a TrainingGroup grid references fields that don't exist."""


def _slugify(name: str) -> str:
    """Normalize a group name into a stable, id-safe slug.

    Lowercased, non-alphanumeric runs collapsed to single hyphens. Raises if
    the name has no usable characters so a typo can't produce an empty id that
    silently merges unrelated runs.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    if not slug:
        raise TrainingGroupError(
            f"group name {name!r} has no alphanumeric characters to form an id"
        )
    return slug


def _is_pydantic_model(obj: Any) -> bool:
    return hasattr(type(obj), "model_fields")


def _valid_fields(obj: Any) -> set[str]:
    """Public, settable field names on ``obj``.

    Recipes and ``TrainConfig`` are (pydantic) dataclasses, so their fields are
    the source of truth. Models/datasets are plain classes that accept kwargs
    via ``setattr``, so we approximate their fields from class annotations and
    class-level attributes across the MRO.
    """
    if _dc.is_dataclass(obj):
        return {f.name for f in _dc.fields(obj) if not f.name.startswith("_")}

    names: set[str] = set()
    if _is_pydantic_model(obj):
        names |= set(type(obj).model_fields)
    for klass in type(obj).__mro__:
        names |= set(getattr(klass, "__annotations__", {}) or {})
    names |= set(vars(obj))
    return {n for n in names if not n.startswith("_")}


def _revalidate_recipe(recipe: Any) -> Any:
    """Rebuild a recipe from its fields to re-run pydantic validation.

    Mutating a field via ``setattr`` bypasses pydantic's type checks, so after
    applying overrides we reconstruct the recipe through its constructor. This
    is the same reconstruction pattern ``train.py:_merge_recipe`` already
    relies on, so it composes cleanly with preset merging done at build time.
    """
    if not _dc.is_dataclass(recipe):
        return recipe
    field_values = {
        f.name: getattr(recipe, f.name)
        for f in _dc.fields(recipe)
        if f.init is not False
    }
    return type(recipe)(**field_values)


class TrainingGroup:
    """A base ``TrainConfig`` plus a grid of field overrides to expand."""

    def __init__(
        self,
        base: TrainConfig,
        grid: dict[str, list[Any]] | None = None,
        *,
        name: str | None = None,
        merge_model_recipe: bool | None = None,
    ) -> None:
        self.base = base
        self.grid: dict[str, list[Any]] = dict(grid or {})
        # When set, force preset merging on/off for every variant. Leave None to
        # inherit whatever the base TrainConfig declares. Turn it off for a
        # complete recipe so train() skips _merge_recipe (which rebuilds the
        # model's base recipe type and can reject fields the subclass widened).
        self.merge_model_recipe = merge_model_recipe
        # The name *is* the group id — pass one to get a stable, human-readable
        # id you can find in the dashboard, or leave it off for an autogenerated
        # one. Names are slugified so they're safe as ids / volume-ish keys.
        self.name = name
        self.group_id = _slugify(name) if name else f"group-{secrets.token_hex(6)}"

        # Results populated by train(): one TrainResult per successful variant,
        # and (overrides, exception) for each variant that raised.
        self.results: list[TrainResult] = []
        self.launches: list[TrainLaunch] = []
        self.failures: list[tuple[dict[str, Any], BaseException]] = []

        # Fail fast on obvious typos at construction time. get_train_configs()
        # repeats this (plus value-level validation) right before training.
        self._validate_grid_shape()
        self._validate_paths()

    # ── Validation ──────────────────────────────────────────────────────────

    def _validate_grid_shape(self) -> None:
        for path, values in self.grid.items():
            if not isinstance(path, str) or not path:
                raise TrainingGroupError(
                    f"grid keys must be non-empty strings, got {path!r}"
                )
            if isinstance(values, (str, bytes)) or not hasattr(values, "__iter__"):
                raise TrainingGroupError(
                    f"grid['{path}'] must be a list of values to sweep, got {type(values).__name__}"
                )

    def _validate_paths(self) -> None:
        """Check every override path resolves to a real field on the base."""
        problems: list[str] = []
        for path in self.grid:
            segments = path.split(".")
            obj: Any = self.base
            for i, seg in enumerate(segments):
                valid = _valid_fields(obj)
                if seg not in valid:
                    prefix = ".".join(segments[: i + 1])
                    suggestion = difflib.get_close_matches(seg, valid, n=3)
                    hint = (
                        f" (did you mean: {', '.join(suggestion)})"
                        if suggestion
                        else ""
                    )
                    problems.append(
                        f"  - '{path}': '{prefix}' is not a field of "
                        f"{type(obj).__name__}{hint}.\n"
                        f"    valid fields: {', '.join(sorted(valid))}"
                    )
                    break
                # Walk into the attribute for the next segment (last hop is the
                # value we'll set, so we don't need to descend past it).
                if i < len(segments) - 1:
                    obj = getattr(obj, seg)
        if problems:
            raise TrainingGroupError(
                "TrainingGroup grid has invalid field paths:\n" + "\n".join(problems)
            )

    # ── Variant expansion ─────────────────────────────────────────────────────

    def iter_variants(self) -> list[tuple[dict[str, Any], TrainConfig]]:
        """Return ``(overrides, config)`` for each point in the grid.

        Same expansion as :meth:`get_train_configs`, but keeps the per-variant
        override dict alongside the config so callers can label/inspect which
        combination produced which run.
        """
        self._validate_paths()
        keys = list(self.grid)
        # Cross-product of all axes; empty grid yields a single (base) variant.
        combos: list[tuple[Any, ...]]
        if keys:
            import itertools

            combos = list(itertools.product(*(self.grid[k] for k in keys)))
        else:
            combos = [()]
        return [
            (dict(zip(keys, combo)), self._build_variant(dict(zip(keys, combo))))
            for combo in combos
        ]

    def get_train_configs(self) -> list[TrainConfig]:
        """Expand the grid into validated, ready-to-run ``TrainConfig``s."""
        return [cfg for _, cfg in self.iter_variants()]

    def _print_variant_plan(
        self, variants: list[tuple[dict[str, Any], TrainConfig]]
    ) -> None:
        for overrides, cfg in variants:
            print(f"[TrainingGroup]   {cfg.training_run_id}: {overrides!r}")

    def _build_variant(self, overrides: dict[str, Any]) -> TrainConfig:
        # Deep-copy the whole base so each variant owns independent model /
        # dataset / recipe objects — mutating one must not leak into another.
        cfg = copy.deepcopy(self.base)
        # The cached training_run_id is per-instance; clear it so each variant
        # computes its own unique id (create_hash adds a timestamp + slug).
        object.__setattr__(cfg, "_stable_id", None)
        cfg.group_id = self.group_id
        cfg.group_overrides = dict(overrides)
        cfg.group_axes = list(self.grid)
        if self.merge_model_recipe is not None:
            cfg.merge_model_recipe = self.merge_model_recipe

        recipe_touched = False
        for path, value in overrides.items():
            segments = path.split(".")
            target: Any = cfg
            for seg in segments[:-1]:
                target = getattr(target, seg)
            setattr(target, segments[-1], value)
            if segments[0] == "recipe":
                recipe_touched = True

        # Re-run pydantic validation on the recipe (type errors, extra="forbid")
        # so a bad override value is caught here, before any training starts.
        if recipe_touched:
            try:
                cfg.recipe = _revalidate_recipe(cfg.recipe)
            except Exception as exc:  # noqa: BLE001 — re-raise with variant context
                raise TrainingGroupError(
                    f"invalid override for variant {overrides!r}: {exc}"
                ) from exc
        return cfg

    # ── Execution ─────────────────────────────────────────────────────────────

    def train(
        self,
        *,
        max_parallel: int = 1,
        continue_on_error: bool = True,
    ) -> list[TrainResult]:
        """Run every variant and return the successful ``TrainResult``s.

        All configs are expanded and validated up front, so invalid fields fail
        before any run launches. With ``max_parallel > 1`` variants run in a
        thread pool — each ``TrainConfig.train()`` is detached and independent,
        so they progress concurrently on Modal. Failures are collected in
        ``self.failures`` (and re-raised immediately if ``continue_on_error`` is
        False) so one bad run doesn't sink the rest of the sweep.
        """
        variants = self.iter_variants()
        results: list[TrainResult] = []
        failures: list[tuple[dict[str, Any], BaseException]] = []

        def _record_failure(overrides: dict[str, Any], exc: BaseException) -> None:
            if not continue_on_error:
                raise exc
            failures.append((overrides, exc))
            print(f"[TrainingGroup] variant {overrides!r} failed: {exc}")

        def _run(overrides: dict[str, Any], cfg: TrainConfig) -> None:
            try:
                results.append(cfg.train(show_output=max_parallel <= 1))
            except BaseException as exc:  # noqa: BLE001 — recorded per-variant
                _record_failure(overrides, exc)

        print(
            f"[TrainingGroup] {self.group_id}: launching {len(variants)} variant(s)"
            + (f" (max_parallel={max_parallel})" if max_parallel > 1 else "")
        )
        self._print_variant_plan(variants)
        if max_parallel <= 1:
            for overrides, cfg in variants:
                _run(overrides, cfg)
        else:
            for i in range(0, len(variants), max_parallel):
                batch = variants[i : i + max_parallel]
                launched: list[tuple[dict[str, Any], TrainLaunch]] = []
                for overrides, cfg in batch:
                    try:
                        launched.append(
                            (
                                overrides,
                                cfg.launch(show_output=False, prepare_inputs=True),
                            )
                        )
                    except BaseException as exc:  # noqa: BLE001
                        _record_failure(overrides, exc)
                for overrides, launch in launched:
                    try:
                        results.append(launch.result())
                    except BaseException as exc:  # noqa: BLE001
                        _record_failure(overrides, exc)

        self.results = results
        self.failures = failures
        print(
            f"[TrainingGroup] {self.group_id}: "
            f"{len(results)} succeeded, {len(failures)} failed"
        )
        return results

    def launch(
        self,
        *,
        continue_on_error: bool = True,
        prepare_inputs: bool = False,
    ) -> list[TrainLaunch]:
        """Start every variant as a detached Modal call and return immediately."""
        variants = self.iter_variants()
        launches: list[TrainLaunch] = []
        failures: list[tuple[dict[str, Any], BaseException]] = []

        print(f"[TrainingGroup] {self.group_id}: launching {len(variants)} variant(s)")
        self._print_variant_plan(variants)
        for overrides, cfg in variants:
            try:
                launch = cfg.launch(
                    show_output=False,
                    prepare_inputs=prepare_inputs,
                )
                launches.append(launch)
                print(
                    f"[TrainingGroup] launched {overrides!r}: "
                    f"{launch.training_run_id} ({launch.modal_app_id})"
                )
            except BaseException as exc:  # noqa: BLE001 — recorded per-variant
                if not continue_on_error:
                    raise
                failures.append((overrides, exc))
                print(f"[TrainingGroup] variant {overrides!r} launch failed: {exc}")

        self.launches = launches
        self.failures = failures
        print(
            f"[TrainingGroup] {self.group_id}: "
            f"{len(launches)} launched, {len(failures)} failed"
        )
        return launches
