"""Generate the README.md Models table from the train recipe registries.

The table is derived from ``__all__`` of
``modal_training_gym.train_recipes.slime_recipe`` and
``...miles_recipe``, so adding a recipe there is the only step needed to get a
model listed.

uv run scripts/generate_models_table.py            # rewrite README.md
uv run scripts/generate_models_table.py --check    # fail if README.md is stale
"""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

from modal_training_gym.common.models import base as models_base

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_README = ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN MODELS TABLE -->"
END_MARKER = "<!-- END MODELS TABLE -->"
BANNER = (
    "<!-- Auto-generated by scripts/generate_models_table.py from the recipe "
    "registries in modal_training_gym/train_recipes/*/__init__.py. Do not edit "
    "by hand. -->"
)

# Framework label → recipe package, in the order frameworks appear in a row.
FRAMEWORKS: dict[str, str] = {
    "slime": "modal_training_gym.train_recipes.slime_recipe",
    "miles": "modal_training_gym.train_recipes.miles_recipe",
}

# Recipe class name suffixes that qualify *how* a model is trained rather than
# naming a different model, stripped before matching a recipe to a ModelConfig.
_QUALIFIER_SUFFIXES = ("LoRA",)


def _model_configs() -> dict[str, type[models_base.ModelConfig]]:
    """Every exported ModelConfig subclass, keyed by lowercased class name."""
    models = importlib.import_module("modal_training_gym.common.models")
    configs: dict[str, type[models_base.ModelConfig]] = {}
    for name in models.__all__:
        obj = getattr(models, name)
        if isinstance(obj, type) and issubclass(obj, models_base.ModelConfig):
            configs[name.lower()] = obj
    return configs


def _model_key(recipe_name: str) -> str:
    """`Kimi_K2_5_LoRA_Recipe` → `kimi_k2_5`, matching a ModelConfig class."""
    stem = recipe_name.removesuffix("_Recipe")
    for qualifier in _QUALIFIER_SUFFIXES:
        stem = stem.removesuffix(f"_{qualifier}")
    return stem.lower()


def collect_models() -> dict[str, list[str]]:
    """Map HuggingFace model name → framework labels that have a recipe for it."""
    configs = _model_configs()
    models: dict[str, list[str]] = {}
    unmatched: list[str] = []

    for framework, module_path in FRAMEWORKS.items():
        module = importlib.import_module(module_path)
        for recipe_name in module.__all__:
            if not recipe_name.endswith("_Recipe"):
                continue
            config = configs.get(_model_key(recipe_name))
            if config is None:
                unmatched.append(f"{module_path}.{recipe_name}")
                continue
            frameworks = models.setdefault(config.model_name, [])
            if framework not in frameworks:
                frameworks.append(framework)

    if unmatched:
        raise SystemExit(
            "No ModelConfig found for these recipes:\n  "
            + "\n  ".join(unmatched)
            + "\nExport a matching ModelConfig from modal_training_gym.common.models "
            "(class name = recipe name without the _Recipe suffix)."
        )
    return models


def render_table(models: dict[str, list[str]]) -> str:
    lines = ["| Model | Framework |", "|---|---|"]
    for model_name in sorted(models):
        frameworks = ", ".join(f"`{f}`" for f in models[model_name])
        lines.append(f"| `{model_name}` | {frameworks} |")
    return "\n".join(lines)


def render_section(models: dict[str, list[str]]) -> str:
    return f"{BEGIN_MARKER}\n{BANNER}\n\n{render_table(models)}\n{END_MARKER}"


def update_readme(readme_path: Path, models: dict[str, list[str]]) -> tuple[str, str]:
    """Return (current content, content with a freshly rendered table)."""
    content = readme_path.read_text()
    if BEGIN_MARKER not in content or END_MARKER not in content:
        raise SystemExit(
            f"Markers {BEGIN_MARKER} / {END_MARKER} not found in {readme_path}"
        )
    before, rest = content.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return content, f"{before}{render_section(models)}{after}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the README.md Models table from the recipe registries."
    )
    parser.add_argument("--readme", type=Path, default=DEFAULT_README)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the table is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    models = collect_models()
    if not models:
        raise SystemExit("No recipes found in the recipe registries")

    current, updated = update_readme(args.readme, models)
    if args.check:
        if current != updated:
            raise SystemExit(
                f"{args.readme} Models table is out of date. Run: "
                "uv run scripts/generate_models_table.py"
            )
        print(f"{args.readme.name} Models table is up to date ({len(models)} models)")
        return

    if current == updated:
        print(f"{args.readme.name} Models table already up to date")
        return
    args.readme.write_text(updated)
    print(f"Wrote {args.readme.name} Models table ({len(models)} models)")


if __name__ == "__main__":
    main()
