"""Generate the Models table in README.md from the train recipe registries.

Each recipe is matched to its `ModelConfig` by class name to recover the
canonical HuggingFace model name, which the class name alone does not encode
(`Qwen3_5_0_8b_Recipe` -> `Qwen3_5_0_8B.model_name` -> `Qwen/Qwen3.5-0.8B`).
Adding a recipe to a registry is therefore the only step needed to list a model.

uv run scripts/generate_models_table.py            # rewrite README.md
uv run scripts/generate_models_table.py --check    # fail if the table is stale
"""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path

from modal_training_gym.common import models

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_README = ROOT / "README.md"

BEGIN_MARKER = "<!-- BEGIN MODELS TABLE -->"
END_MARKER = "<!-- END MODELS TABLE -->"
BANNER = (
    "<!-- Auto-generated by scripts/generate_models_table.py from the recipe "
    "registries in modal_training_gym/train_recipes/*/__init__.py. Do not edit "
    "by hand. -->"
)

# Framework label → recipe package, in the order frameworks appear in a row.
FRAMEWORKS: dict[str, str] = {
    "slime": "modal_training_gym.train_recipes.slime_recipe",
    "miles": "modal_training_gym.train_recipes.miles_recipe",
}

# Model configs keyed by lowercased class name, for recipe name lookup.
MODEL_CONFIGS = {name.lower(): getattr(models, name) for name in models.__all__}


def _model_key(recipe_name: str) -> str:
    """`Kimi_K2_5_LoRA_Recipe` → `kimi_k2_5`, a ModelConfig class name.

    `_LoRA` qualifies how a model is trained rather than naming a different
    model, so it is dropped along with the `_Recipe` suffix.
    """
    return recipe_name.removesuffix("_Recipe").removesuffix("_LoRA").lower()


def collect_models() -> dict[str, list[str]]:
    """Map HuggingFace model name → framework labels that have a recipe for it."""
    table: dict[str, list[str]] = {}
    unmatched: list[str] = []

    for framework, module_path in FRAMEWORKS.items():
        registry = importlib.import_module(module_path)
        for recipe_name in registry.__all__:
            if not recipe_name.endswith("_Recipe"):
                continue
            config = MODEL_CONFIGS.get(_model_key(recipe_name))
            model_name = getattr(config, "model_name", None)
            if not model_name:
                unmatched.append(f"{module_path}.{recipe_name}")
                continue
            frameworks = table.setdefault(model_name, [])
            if framework not in frameworks:
                frameworks.append(framework)

    if unmatched:
        raise SystemExit(
            "No ModelConfig found for these recipes:\n  "
            + "\n  ".join(unmatched)
            + "\nExport a matching ModelConfig from modal_training_gym.common.models "
            "(class name = recipe name without the _Recipe suffix)."
        )
    return table


def render_section(table: dict[str, list[str]]) -> str:
    rows = [
        f"| `{model_name}` | {', '.join(f'`{f}`' for f in table[model_name])} |"
        for model_name in sorted(table)
    ]
    return "\n".join(
        [BEGIN_MARKER, BANNER, "", "| Model | Framework |", "|---|---|", *rows]
        + [END_MARKER]
    )


def rendered_readme(readme_path: Path, table: dict[str, list[str]]) -> tuple[str, str]:
    """Return (current README content, content with a freshly rendered table)."""
    content = readme_path.read_text()
    if BEGIN_MARKER not in content or END_MARKER not in content:
        raise SystemExit(
            f"Markers {BEGIN_MARKER} / {END_MARKER} not found in {readme_path}"
        )
    before, rest = content.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return content, f"{before}{render_section(table)}{after}"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the Models table in README.md from the recipe registries."
    )
    parser.add_argument("--readme", type=Path, default=DEFAULT_README)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the table is out of date instead of rewriting it.",
    )
    args = parser.parse_args()

    table = collect_models()
    if not table:
        raise SystemExit("No recipes found in the recipe registries")

    current, updated = rendered_readme(args.readme, table)
    if args.check:
        if current != updated:
            raise SystemExit(
                f"{args.readme} Models table is out of date. Run: "
                "uv run scripts/generate_models_table.py"
            )
        print(f"Models table is up to date ({len(table)} models)")
        return

    if current != updated:
        args.readme.write_text(updated)
    print(f"Wrote Models table ({len(table)} models)")


if __name__ == "__main__":
    main()
