name: CI/CD


on:
  pull_request:
  merge_group:
    types: [checks_requested]


jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v8.1.0

      - name: Ruff check
        run: uv run --group dev ruff check modal_training_gym/

      - name: Ruff format
        run: uv run --group dev ruff format --check modal_training_gym/
